# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElevatorAction' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElevatorAction 
	pod ‘SwiftR’ 
	pod ’SwiftCharts’, :git => 'https://github.com/i-schuetz/SwiftCharts.git'
	pod 'HockeySDK', '~> 4.1.5' 

  target 'ElevatorActionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
